title: Pedro Coelho # your name (or website title) here
logo: "/images/Logo_urahara.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <style> body {text-align: justify} </style>
  Hi, my name is Pedro and I'm a game developer with a passion for creating immersive interactive experiences. I'm currently deepening my knowledge through a Master's Degree in Digital Games at the University of Aveiro. This is my space to share the projects I've been working on and show a little of my journey in the world of game development.
  <br><br>
  Email: <a href="mailto:pedrocoelho485@gmail.com">pedrocoelho485@gmail.com</a>
  <br><br>
  <a href="https://www.linkedin.com/in/pedrocoelho485/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
include:
  - _includes/head-custom.html